#!/usr/bin/env python

r"""Hyde: Server for static website.

   _______     ___
+ 6 @ |||| # P ||| +

"""

from flask import Flask

##
# Top-level entry point
##
@app.route('/')
def index():
    return "Welcome to Gkeyll!"

if __name__ == "__main__":
   app.run(host='localhost', port=os.environ.get('PORT', 3000), debug=False)
