#!/usr/bin/env python

from flask import Flask
import hyde
import os

app = Flask(__name__)

simManager = hyde.SimManager()
userManager = hyde.UserManager()

@app.route('/')
def index():
    return "Hello, World!"

@app.route('/api/users')
def getUsers():
   userNms = ""
   
   users = userManager.getUsers()
   for uId in users:
      u = hyde.User(uId)
      userNms = userNms + u.name() + " "

   return userNms

@app.route('/api/user')
def getUser():
   userNms = ""
   
   users = userManager.getUsers()
   for uId in users:
      u = hyde.User(uId)
      userNms = userNms + u.name() + "; "

   return userNms

if __name__ == "__main__":
   app.run(host='localhost', port=os.environ.get('PORT', 3000), debug=False)
