#!/usr/bin/env python

r"""Hyde: Server for REST API and static website.

   _______     ___
+ 6 @ |||| # P ||| +

"""

from flask import Flask
import hyde
import os
import json

app = Flask(__name__)

simManager = hyde.SimManager()
userManager = hyde.UserManager()

##
# Top-level entry point
##
@app.route('/')
def index():
    return "Welcome to Gkeyll!"

## 
# User management API
##
 
@app.route('/api/users')
def api_getAllUsers():
   users = { }
   
   userIds = userManager.getUsers()
   for uId in userIds:
      u = hyde.User(uId)
      users[uId] = {
         'name' : u.name(),
         'group' : u.group(),
         'dateCreated' : u.dateCreated()
      }

   return json.dumps(users)

@app.route('/api/user')
def api_getUser():
   userNms = ""
   
   users = userManager.getUsers()
   for uId in users:
      u = hyde.User(uId)
      userNms = userNms + u.name() + "; "

   return userNms

if __name__ == "__main__":
   app.run(host='localhost', port=os.environ.get('PORT', 3000), debug=False)
